version: '3.7'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_INITDB_ARGS: --auth-host=scram-sha-256
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: fin_api
    ports:
      - 5432:5432
